"use client";

import { useEffect, useRef } from "react";
import { Product } from "@/types/product.types";
import CanvasModel from "@/components/canvas";
import { useCheckoutContext } from "@/components/contexts/AppContext/CheckoutContext";
import ProductPageLayout from "@/components/layout/ProductPageLayout";
import ProductCustomization from "@/components/ProductConfigurator/ProductCustomization";
import {
  useParams,
  usePathname,
  useRouter,
  useSearchParams,
} from "next/navigation";
import { garmet } from "@/products";
import ProductDesignCreation, {
  ProductDesignCreationRef,
} from "@/components/features/product/ProductSelection/ProductDesignCreation";
import { useDesignSessionListener } from "@/db/design-sessions";

export default function Page() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const pathname = usePathname();
  const designSessionId = useParams()?.designSessionId as string;
  const prompt = searchParams.get("opis") || "";
  const createPromptRef = useRef<ProductDesignCreationRef>(null);
  const isAutoGenerated = useRef(false);

  const {
    onOpen: openCheckout,
    productsAmount,
    item,
    setItem,
  } = useCheckoutContext();
  const productId = "ustvari-svoj-motiv";
  const productName = "Ustvari svoj motiv";

  const [data] = useDesignSessionListener(designSessionId);

  useEffect(() => {
    const sizes = garmet.sizes;
    // Initialize product configuration
    const quantities = Object.fromEntries(sizes.map((size) => [size, 0]));
    setItem({
      productId,
      name: productName,
      color: garmet.colors[0].hex,
      designUrl: "",
      // designUrl:
      //   "https://firebasestorage.googleapis.com/v0/b/kreativko---development.firebasestorage.app/o/miMceISWCgaJ00yyVLfeXAUaEb73%2F1760025709663_ai_generated.png?alt=media&token=5382d01a-7d47-434a-b01f-74cd7bf6ecc4",
      quantities,
    });
  }, [setItem]);

  useEffect(() => {
    if (
      !data ||
      isAutoGenerated.current ||
      data.createdDesigns.length > 0 ||
      !prompt
    )
      return;

    isAutoGenerated.current = true;

    createPromptRef.current?.generateDesign(prompt, data.uploadedAssets);

    router.replace(pathname);
  }, [data, prompt, router, pathname]);

  const { quantities, color, designUrl } = item;

  if (!data) return null;

  const onDesignSelect = (imageUrl: string) => {
    setItem((i) => ({ ...i, designUrl: imageUrl }));
  };

  return (
    <ProductPageLayout
      title="Ustvari svoj motiv"
      description="Opiši željen motiv, dodaj slike in ustvari svoj unikatni motiv."
      leftColumn={
        <>
          <ProductDesignCreation
            designSession={data}
            ref={createPromptRef}
            onDesignSelect={onDesignSelect}
            selectedDesignUrl={designUrl}
            initialPrompt={prompt}
          />
          <ProductCustomization
            name="Ustvari svoj motiv"
            quantities={quantities}
            onColorChange={(c) => setItem({ ...item, color: c })}
            onSizeChange={(size, value) =>
              setItem({
                ...item,
                quantities: { ...quantities, [size]: value },
              })
            }
            productsAmount={productsAmount}
            onCheckout={openCheckout}
            productId={productId}
            color={color}
            isCheckoutDisabled={!designUrl || productsAmount === 0}
          />
        </>
      }
      rightColumn={
        <div className="w-full max-w-full overflow-hidden">
          <div className="aspect-square w-full mx-auto">
            <CanvasModel
              product={Product.Shirt}
              color={color}
              frontPatternUrl={designUrl}
            />
          </div>
        </div>
      }
    />
  );
}
