/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/mug.glb 
Author: roabon (https://sketchfab.com/roabon)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mug-63025070788b4cffb4ad93b6b19b7fb0
Title: Mug
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mug.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['Mug_again_191,191,191_0'].geometry} material={materials['191191191']} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/mug.glb')
