"use client";

import { useEffect, useRef, useState } from "react";
import { Product } from "@/types/product.types";
import CanvasModel from "@/components/canvas";
import { useCheckoutContext } from "@/components/contexts/AppContext/CheckoutContext";
import { productConfig } from "@/products";
import ProductPageLayout from "@/components/layout/ProductPageLayout";
import PromptCreator from "@/components/ProductConfigurator/PromptCreator";
import ProductCustomization from "@/components/ProductConfigurator/ProductCustomization";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { PromptCreatorRef } from "@/components/ProductConfigurator/PromptCreator/PromptCreator";

export default function Page() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const pathname = usePathname();
  const sizes = productConfig.sizes;
  const createPromptRef = useRef<PromptCreatorRef>(null);
  // TODO: is there a better solution to this??
  const isAutoGenerated = useRef(false);

  const {
    onOpen: openCheckout,
    productsAmount,
    item,
    setItem,
  } = useCheckoutContext();
  const productId = "ustvari-svoj-motiv";
  const productName = "Ustvari svoj motiv";

  const { quantities, color, designUrl } = item;

  useEffect(() => {
    const prompt = searchParams.get("opis");
    if (prompt && !isAutoGenerated.current) {
      isAutoGenerated.current = true;
      createPromptRef.current?.handleGenerateMotif(prompt);
      createPromptRef.current?.setPrompt(prompt);
      // Remove the query param from the URL
      router.replace(pathname);
    }
  }, [searchParams, pathname, router]);

  useEffect(() => {
    // Initialize product configuration
    const quantities = Object.fromEntries(sizes.map((size) => [size, 0]));
    setItem({
      productId,
      name: productName,
      color: "#FFFFFF",
      designUrl:
        "https://firebasestorage.googleapis.com/v0/b/kreativko---development.firebasestorage.app/o/miMceISWCgaJ00yyVLfeXAUaEb73%2F1760025709663_ai_generated.png?alt=media&token=5382d01a-7d47-434a-b01f-74cd7bf6ecc4",
      quantities,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onDesignSelect = (imageUrl: string) => {
    setItem((i) => ({ ...i, designUrl: imageUrl }));
  };

  return (
    <ProductPageLayout
      title="Ustvari svoj motiv"
      description="Opiši motiv, izberi barvo in velikost ter naroči svojo unikatno majico."
      leftColumn={
        <PromptCreator ref={createPromptRef} onDesignSelect={onDesignSelect} />
      }
      centerColumn={
        <div className="w-full max-w-full overflow-hidden">
          <div className="aspect-square w-full mx-auto">
            <CanvasModel
              product={Product.Shirt}
              color={color}
              frontPatternUrl={designUrl}
            />
          </div>
        </div>
      }
      rightColumn={
        <ProductCustomization
          name="Ustvari svoj motiv"
          quantities={quantities}
          onColorChange={(c) => setItem({ ...item, color: c })}
          onSizeChange={(size, value) =>
            setItem({
              ...item,
              quantities: { ...quantities, [size]: value },
            })
          }
          productsAmount={productsAmount}
          onCheckout={openCheckout}
          productId={productId}
          color={color}
        />
      }
    />
  );
}
