/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/pen.glb 
Author: Liza (https://sketchfab.com/lizazebubu)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pen-0b95efcef413435cbb187801ace30932
Title: Pen
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export function Pen() {
  const { nodes, materials } = useGLTF("/assets/pen.glb");
  return (
    <group dispose={null}>
      <group scale={0.01}>
        <group scale={0.09}>
          <mesh
            geometry={(nodes.Cylinder_Material001_0 as THREE.Mesh).geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={(nodes.Cylinder001_Material_0 as THREE.Mesh).geometry}
            material={materials.Material}
          />
          <mesh
            geometry={(nodes.Cylinder002_Material002_0 as THREE.Mesh).geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={(nodes.Cylinder003_Material003_0 as THREE.Mesh).geometry}
            material={materials["Material.003"]}
          />
        </group>
      </group>
    </group>
  );
}
